# .github/workflows/deploy_preview.yml
name: Deploy PR previews

on:
  workflow_run:
    workflows: [netlify_build_docs]
    types: [completed]

permissions:
  contents: write
  actions: read
  pull-requests: write
  pages: write
  statuses: write
  id-token: write

jobs:
  deploy-preview:
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    uses: PazerOP/pr-preview-action/.github/workflows/pr-preview-action-ghp.yml@4499064eaedb2694468204bbbc4fb04bdcd3284f
    with:
      artifact-name: build-${{ github.event.workflow_run.head_sha }}
      workflow-run-id: ${{ github.event.workflow_run.id }}
    secrets: inherit
