# .github/workflows/deploy_preview.yml
name: Deploy PR previews

on:
  workflow_run:
    workflows: [netlify_build_docs]
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  pages: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from triggering run
        uses: actions/download-artifact@v4
        with:
          name: build-${{ github.event.workflow_run.head_sha }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
          path: ./docs

      - name: Deploy PR preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./docs
          action: deploy
          pr-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          token: ${{ github.token }}
